### ISSUE TITLE
Decrypting multiple stanzas

### ISSUE THREAD

**Issue by highesteem** [olastor/age-plugin-fido2-hmac#14]
Hi again,
Attempting to decrypt files encrypted with multiple public keys throws the error:
age: error: fido2-hmac plugin: Decrypting multiple stanzas not supported

Both a regular age private key and the age-se-plugin (remko/age-se-plugin) decrypt multiple stanzas just fine.

**Comment by olastor** [comment]
@highesteem Right, it shouldn't throw that error. That looks like a bug, and my tests didn't cover multiple stanzas. Thanks for spotting it!

**Comment by olastor** [comment]
@highesteem I removed this error as the implementation does handle multiple stanzas. I assume that error I added initially and forgot to remove it. Can you please check the latest release? Please feel free to reopen or open more issues if it still doesn't work.

**Comment by highesteem** [comment]
The bug is gone in the latest release, thanks!
