### ISSUE TITLE
`age-plugin-fido2-hmac --version` not working properly, just prints the help menu.

### ISSUE THREAD

**Issue by multivac61** [olastor/age-plugin-fido2-hmac#19]

**Comment by olastor** [comment]
@multivac61 Thanks for noticing it. You were not using the pre-built binary (there it builds with a version number), right? I fixed the default `make build` command to also include a version number when building locally in https://github.com/olastor/age-plugin-fido2-hmac/commit/ef81e6745ef085df57e8fc659bd8bf6010c3b4eb.

**Comment by multivac61** [comment]
Nice, no I packaged the plugin for nix and noticed the version didn't get through the build.
