### ISSUE TITLE
Support multiple identities

### ISSUE THREAD

**Issue by mntn-xyz** [olastor/age-plugin-fido2-hmac#22]
Best practices for security keys suggest that you should have more than one key, so that a backup is always available if a key is lost or destroyed. Passage has a [PR](https://github.com/FiloSottile/passage/pull/52) open that would support multiple identities, so passwords will be created with multiple recipients (one for each security key) and decryption can be handled transparently regardless of which identity/key is available.

The PR in question adds a `AGE_IDENTITY_ARGS` var containing multiple identities, for use with plugins that support it. It continues to provide `IDENTITIES_FILE` as a fallback, but this will only contain a single identity for compatibility (the first one in the list). `AGE_IDENTITY_ARGS` seems like a good approach, but I wanted to point this out now in case you had any thoughts or feedback on the PR.

**Comment by remko** [comment]
@mntn-xyz The PR you reference (and the vars you describe) only relates to Passage plugins. It has no impact on age plugins.

**Comment by olastor** [comment]
@mntn-xyz I am not so familiar with passage, but I will try to understand the context here better. In general, recipients and identities are passed from the main age process to the downstream plugins and the plugins are only responsible for correctly wrapping or unwrapping a file key recipients or an identity. I am not sure what passage plugins are and how they relate to this.

**Comment by mntn-xyz** [comment]
@remko @olastor Passage plugins are age plugins, as passage is just a slim wrapper for age (really just a shell script). The purpose of passage is to simplify/wrap age for managing a collection of encrypted passwords. However, I now think this issue is irrelevant due to this conversation which I am just now seeing: https://github.com/str4d/rage/issues/414#issuecomment-1925463164

This discussion suggests that multiple -i flags should be supported by the age/rage CLI, with identities read left-to-right. Age/rage would then call any plugins once per identity. In other words this is not really a plugin issue and can be closed.
